유형	기호	목적
확장	<|--	계층 구조에서 클래스의 특수화. 상속
구현	<|..	클래스에 의한 인터페이스의 실현
컴포지션	*--	부분이 전체 없이는 존재할 수 없음. LogManager없이 Log 존재 못함.
집합	o--	부분이 전체와 독립적으로 존재할 수 있음. Field 없어도 Ant는 존재
의존성	-->	객체가 다른 객체를 사용함. 멤버 변수로 다른 클래스와 연관이 있을 때
약한 의존성	..>	더 약한 형태의 의존성. 파라미터나 반환에 사용되는 클래스 관계를 나타낼 때(로컬 변수, 파라미터, 반환 값으로 호출되는 메소드가 실행되는 동안에만 유지가 될 때)

개미 시뮬레이션 uml

@startuml 클래스 구조도
title 개미 시뮬레이션 클래스 구조도

class Ant{

}

class Food{

}

class GameObject{

}

class Field{

}

class LogManager{

}

struct Log{

}

class GameManager{
Update()
Draw()
}

Ant --|> GameObject
Food --|> GameObject

LogManager *-- Log

note top of GameManager : main에서 동작\n개미 음식 필드 로그 모든 것 관리
GameManager --> LogManager
GameManager --> Ant
GameManager --> Food
GameManager --> Field

@enduml